usuarios = [
        {"nombre": "Sara", "apellidos": "Clavero Gimeno", "usuario": "sclavero", "puesto": "Administrador/a"},
        {"nombre": "Fernando", "apellidos": "Abadía Burguete", "usuario": "fabadia", "puesto": "Administrador/a"},
        {"nombre": "Mª Pilar", "apellidos": "Ibáñez Figueroba", "usuario": "mpibannezf", "puesto": "ADM"},
        {"nombre": "Valentín", "apellidos": "Gargallo Valero", "usuario": "vgargallo", "puesto": "ADM"},
        {"nombre": "Saul", "apellidos": "Yangüela Salinas", "usuario": "syanguela", "puesto": "ADM"},
        {"nombre": "Ruth", "apellidos": "Grasa Molina", "usuario": "rgrasam", "puesto": "ADM"},
        {"nombre": "Mónica", "apellidos": "Lopes Da Silva", "usuario": "mlopesdasilva", "puesto": "ADM"},
        {"nombre": "Rodrigo", "apellidos": "González García", "usuario": "rgonzalezg", "puesto": "TS"},
        {"nombre": "Isabel", "apellidos": "Caro Iñáñez", "usuario": "icaro", "puesto": "TS"},
        {"nombre": "Ana", "apellidos": "Benedicto Bellido", "usuario": "ambenedicto", "puesto": "TS"},
        {"nombre": "Raquel", "apellidos": "Lozano Ibáñez", "usuario": "rlozanoi", "puesto": "TS"},
        {"nombre": "Ana", "apellidos": "Rodriguez Remón", "usuario": "arodriguezrem", "puesto": "TS"},
        {"nombre": "Raquel", "apellidos": "Ipas Lagraba", "usuario": "ripas", "puesto": "TS"},
        {"nombre": "Verónica", "apellidos": "Delgado Hernández", "usuario": "vdelgado", "puesto": "TS"},
        {"nombre": "Patricia", "apellidos": "Pérez Mora", "usuario": "pperezmo", "puesto": "TS"},
        {"nombre": "Candela", "apellidos": "Sauras Tris", "usuario": "csaurast", "puesto": "TS"},
        {"nombre": "Nieves", "apellidos": "García Antolínez", "usuario": "mngarciaa", "puesto": "TS"},
        {"nombre": "Susana", "apellidos": "Broc Martínez", "usuario": "sbroc", "puesto": "TS"},
        {"nombre": "Marga", "apellidos": "Garces Felipe", "usuario": "mgarcesf", "puesto": "TS"},
        {"nombre": "Marta", "apellidos": "Gómez Amores", "usuario": "mmgomeza", "puesto": "TS"},
        {"nombre": "Izarbe", "apellidos": "Gil Romero", "usuario": "imgilr", "puesto": "TS"},
        {"nombre": "Sandra", "apellidos": "Carrillo Solanas", "usuario": "scarrillos", "puesto": "TS"},
        {"nombre": "Belén", "apellidos": "Herrero Marín", "usuario": "bherrero", "puesto": "TS"},
        {"nombre": "María", "apellidos": "Gasca Noguera", "usuario": "mgascan", "puesto": "TS"},
    ]
